# Generated by Django 4.2.17 on 2025-01-21 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arches_ciim_app', '0002_add_plugin'),
    ]

    def update_all_relatededitlogids(apps, schema_editor):
        """
        Function to update all existing LREs.  If many in the database, this migration could take a while.
        """
        EditLog = apps.get_model("models", "EditLog")
        LatestResourceEdit = apps.get_model("arches_ciim_app", "LatestResourceEdit")

        lres = LatestResourceEdit.objects.all()
        for lre in lres:
            edit = EditLog.objects.order_by('resourceinstanceid', '-timestamp').distinct('resourceinstanceid').get(resourceinstanceid=lre.resourceinstanceid)
            lre.relatededitlogid = edit
            lre.save()

    operations = [
        migrations.RenameField(
            model_name='latestresourceedit',
            old_name='editlogid',
            new_name='latestresourceeditid',
        ),
        migrations.AddField(
            model_name='latestresourceedit',
            name='relatededitlogid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.editlog'),
        ),
        migrations.RunPython(update_all_relatededitlogids, None)
    ]
